### ISSUE TITLE
Direct output to mounted volume in output-filer

### ISSUE THREAD

**Issue by Myskmadra** [EMBL-EBI-TSI/TESK#114]
Hey,

I was looking for an answer to this question and was toying around with different things but I did not get it to work. I have a volume mounted at `/transfer` and would like output-filer to move the generated files there. The files I am interested are located in `/tes`. I modified the example `output.json` but I am clearly doing something wrong:

```
{
  "description": "Test",
  "outputs": [
    {
      "description": "Test",
      "path": "/tes/file1.txt",
      "type": "FILE",
      "url": "file:///transfer/file1.txt"
    },
    {
      "description": "Test",
      "path": "/tes/file2.txt",
      "type": "FILE",
      "url": "file:///transfer/file2.txt"
    }
  ],
  "executors": [
    {
      "image": "alpine",
      "command": [
        "echo",
        "This goes to file1"
      ],
      "stdout": "/tes/file1.txt"
    },
    {
      "image": "alpine",
      "command": [
        "sh",
        "-c",
        "echo 'This goes to file2' > /tes/file2.txt"
      ]
    }
  ]
}
```

The output-filer checks the url-field and complains that it should be a descendant `/tmp` but I don't want a hostpath there. I want it to transfer the files from `/tes` to `/transfer`. As I said, the volume is successfully mounted and I can write manually to the folder. Any input is highly appreciated.

**Comment by aniewielska** [comment]
The shared file system solution allows to mount the shared storage at different paths at workflow manager side and at TESK side.  There are 2 environment variables of controlling the behaviour:
```
- name: TESK_API_TASKMASTER_ENVIRONMENT_HOST_BASE_PATH
          value: /tmp

        - name: TESK_API_TASKMASTER_ENVIRONMENT_CONTAINER_BASE_PATH
          value: /transfer
```
The `TESK_API_TASKMASTER_ENVIRONMENT_HOST_BASE_PATH` is on the workflow manager side. The workflow manager produces the input and output paths in TES requests. The solution will work as long as the workflow manager uses paths relative to the shared PVC mount root (in this case `/tmp`). For some workflow managers it is a current directory of its execution.
TESK mounts the shared  PVC under  TESK_API_TASKMASTER_ENVIRONMENT_CONTAINER_BASE_PATH, but expects paths relative to TESK_API_TASKMASTER_ENVIRONMENT_HOST_BASE_PATH and translates them internally.
In you case, you can either change the `TESK_API_TASKMASTER_ENVIRONMENT_HOST_BASE_PATH` to `/transfer` or change the paths in the example to relative to `/tmp`.
