### ISSUE TITLE
User Story: Demonstrate distributed workflow execution

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#14]
As a **user**, I **would like to** showcase the whole/part execution of the MMG-CWL workflow on two or more compute sites to my stakeholders **so that** I can track the progress of this product’s development and engage new stakeholder to the project.

**Comment by aniewielska** [comment]
That finally succeeded for multi step workflow being a subset of the full MMG-CWL workflow.
The current running multi step workflow stemming from MMG is here: 
https://github.com/EMBL-EBI-TSI/workflow-is-cwl/blob/master/workflows/cmsearch-multimodel-wf.cwl
