### ISSUE TITLE
User Story: GA4GH Workflow Execution Showcase

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#15]
As a **user**, I **would like to** showcase a full end-to-end MMG-CWL and/or MMETSP workflow at the GA4GH 6th Plenary by Oct 2018, **so that** I can further my research publication objectives and engage with the global standards initiative.

**Comment by aniewielska** [comment]
We presented successfully at the plenary with a multi-step workflow, that was created by MMG team.
