### ISSUE TITLE
Architecture picture and description are out of date

### ISSUE THREAD

**Issue by erikvdbergh** [EMBL-EBI-TSI/TESK#26]

**Comment by erikvdbergh** [comment]
Updated description & doc. If someone could review and close that would be appreciated.

**Comment by psafont** [comment]
The text looks good to me.

As a nitpick taskmaster is mentioned as task controller in the picture, will this be confusing to people?

**Comment by aniewielska** [comment]
We actually have only one PVC per task, right? So there is no such a thing as a main one (text) and picture suggests many of them. And Global PV is rather a Storage Class (because each PVC creates its own PV dynamically - there is no global PV as such).

**Comment by aniewielska** [comment]
Plus I support picking only one name for taskmaster (taskmaster or task controller).

**Comment by erikvdbergh** [comment]
Okay updated as per comments. I tried representing the fact that there is only one pod at a time with dashed lines & color. I want to make sure that it is clear it is a multi-step thing.

**Comment by aniewielska** [comment]
I like it! If there are no further comments, we can move it to Done.

**Comment by susheel** [comment]
Looks good to me.
