### ISSUE TITLE
Explore cwl-tes as an exemplar CWL Runner

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#34]
See: https://github.com/common-workflow-language/cwl-tes

**Comment by erikvdbergh** [comment]
Example QC workflow:
https://github.com/EBI-Metagenomics/ebi-metagenomics-cwl/blob/master/workflows/emg-qc-single.cwl
Has 3 steps in total so fairly reasonable, this should be the target cwl we want to run with this story.
