### ISSUE TITLE
Register OIDC Client to access ELIXIR AAI tokens

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#35]
See: [ELIXIR OIDC Registration](https://login.elixir-czech.org/oidc/manage/dev/dynreg)
See: [ELIXIR OIDC Dev Guide](https://docs.google.com/document/d/1vOyW4dLVozy7oQvINYxHheVaLvwNsvvghbiKTLg7RbY)

**Comment by aniewielska** [comment]
- [ ] Register a test client of ELIXIR AAI
- [ ] Expose the client for internal use (investigate options Embassy/Kubernetes)
- [ ] Request a change of callback IP

**Comment by aniewielska** [comment]
At the moment we decided not to expose the client anywhere, so it stays in my private repo: https://gitlab.ebi.ac.uk/aniewielska/elixir-client.
The client is registered by Elixir and runs 'in production' - I (aniewielska) and fake Teodor can both obtain access tokens using it and the userinfo endpoint returns profile and groupNames data. Though, the registration process (forms) is in progress, so 'in production' status may be revoked and we may come back to proper Elixir TEST VO?
