### ISSUE TITLE
Retrieve group membership scopes from ELIXIR AAI

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#37]
- [x] Investigate if `groupNames` is available in the ELIXIR AAI token
- [x] Use TESK group name to restrict access to the API 
- [x] Store ownership information (owing USER and GROUP) with task
- [x] Manual testing
- [x] Unit/Integration tests
- [x] Document design
- [x] (Optional) investigate Swagger UI/SpringFox  integration with OAuth2

Please elaborate this task with further sub-tasks as necessary

**Comment by aniewielska** [comment]
Quick notes - should end up in a proper document:
1. There is a scope _groupNames_ and is required to access group membership info. Just that the information is not available in any of the tokens (nor access, neither id), but in the user info endpoint. So we will hit that endpoint for each request to TESK.

1. We came up with such privs design:

- to create a task, a user has to be a member of `elixir:GA4GH:GA4GH-CAP:EBI` group and EBI will indicate an environment/installation of TESK.
- we will introduce _organisational_ groups, which will be direct subgroups of `elixir:GA4GH:GA4GH-CAP:EBI`. Admins of such groups will be saved as members of subgroup with a name ADMIN (so for `elixir:GA4GH:GA4GH-CAP:EBI:SDO` group, members of  `elixir:GA4GH:GA4GH-CAP:EBI:SDO:ADMIN` will be SDO admins. Members of `elixir:GA4GH:GA4GH-CAP:EBI:ADMIN` will be treated specially - as global admins.
- each task will be owned by one user and (at most) one group. If user belongs to more than one groups, they would have to choose at the time of task creation, for each group they create the task.
- a user will be able to see and/or cancel a task, if any of the below is true:
-- user is a _global_ admin (a member of `elixir:GA4GH:GA4GH-CAP:EBI:SDO:ADMIN`)
--user owns a task (created it) and (still) belongs to a group owning the task
--user is an admin of a group owning the task
--user as a _global_ admin.
3. We will store owning group and user_id as K8S labels (problems already appeared - label values have restricted characters) and for list query use label selectors, whenever possible.
1. We will return owning group and user_id as TES `logs.metadata`

**Comment by aniewielska** [comment]
Tested by @erikvdbergh (as we prepare for Elixir All Hands)
Identified issue: swagger UI cancel - fixed.
Request for debug mode for taskmaster - done.
