### ISSUE TITLE
As a user I would like the workflow engine to support remote transputs (input/outputs)

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#50]
Basic Support:
- HTTP (read-only)
- FTP
- S3

**Comment by aniewielska** [comment]
HTTP as source of inputs works for TESK and also for cwl-tes/WES-ELIXIR.
FTP works for TESK and cwl-tes/WES-ELIXIR and Cromwell.
S3 has not been implemented in TESK (and does not work for cwl-tes/WES-ELIXIR and probably also does not work with Cromwell with TES backend - but that was not tested).
I am closing this one, as there is a separate issue for S3.
