### ISSUE TITLE
Register another Elixir AAI client for Swagger UI at CSC

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#52]

**Comment by aniewielska** [comment]
- [ ] Register a client at Elixir AAI; this time for Implicit Grant (Flow)

- [ ] Test cooperation of TESK's swagger UI with Elixir's Implicit Flow. Make amendments, if needed

- [ ] Expose client ID as Kubernetes Secret and add it to TESK API deployment
