### ISSUE TITLE
Tasks remains QUEUED in CSC Cluster

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#54]
https://tesk.c01.k8s-popup.csc.fi/v1/tasks/task-107ccecb?view=MINIMAL

**Comment by erikvdbergh** [comment]
Was related to ftp secret not being populated. Now fixed.

**Comment by aniewielska** [comment]
Also just discovered `optional ` flag for env var from secrets and introduced that for ftp-secret.
