### ISSUE TITLE
Make OAuth authorization/authentication optional (let's switch it all off!)

### ISSUE THREAD

**Issue by aniewielska** [EMBL-EBI-TSI/TESK#57]
Implement a switch, that disables auth completely reverting it to state equivalent to that before auth implementation. May be useful for other potential users of TESK installing it and testing installation and/or unwilling to integrate with Elixir and for us for test purposes and/or in case Elixir dies.
Things to consider:
- switch off authN/Z - possibly by spring profile
- make saving user/group data and constructing user/group-aware label selectors optional (possibly move it to some component, too)

**Comment by susheel** [comment]
Yes, I think this is the functionality we expect. Verified yesterday in the DEMO deployment.
