### ISSUE TITLE
Support remote step inputs and outputs for CWL-TES

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#64]
- [x] [Design doc](https://docs.google.com/document/d/1xrtCK0hemf_iFQ472voH_H-E7cQPRxcnM53rKYIJH34/edit)
- [ ] Remote Storage support
    - Assume user comes with user storage FTP, S3, GridFTP)
- [ ] Dealing with user credentials 
    - Assume user comes with delegated temporary creds

**Comment by susheel** [comment]
Following up with Steven and Tommi for MC support

**Comment by aniewielska** [comment]
That has been implemented in the form of FTP support, but with shared credentials (so user cannot bring their own FTP account).
