### ISSUE TITLE
Adapt CWL-TES to support Remote I/O

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#65]
The original [CWL-TES](https://github.com/common-workflow-language/cwl-tes) implementation with its underlying [cwltool](https://github.com/common-workflow-language/cwltool) dependency assumes the availability of some local shared volume storage to perform checks on task output files between task executions. The current [TESK](https://github.com/EMBL-EBI-TSI/TESK) implementation uses a distributed environment for task execution and exclusively assumes the availability of a remote shared storage to stage/unstage files for task execution. An example TES endpoint is available here: [https://tes-dev.tsi.ebi.ac.uk](http://tes.tsi.ebi.ac.uk/), with an [example TES request](https://docs.google.com/document/d/1xrtCK0hemf_iFQ472voH_H-E7cQPRxcnM53rKYIJH34/edit).

This task aims to adapt the CWL-TES code to support intermediate remote inputs and outputs to allow CWL-TES to be used to execute an entire CWL workflow exclusively using only remote storage. An initial attempt at modification is available [here](https://github.com/erikvdbergh/cwl-tes/tree/mmg).

A user should be able to define base URL for intermediate remote storage by passing a command line parameter to CWL-TES (e.g. `--remote-storage-url='ftp://ftp-private.ebi.ac.uk/tesk'`)

Priority-wise, the FTP protocol should be supported as an initial test case, and the functionality should be extended to other protocols, S3 and finally GridFTP.

An [example CWL pipeline](https://github.com/EBI-Metagenomics/ebi-metagenomics-cwl) for execution on using the CWL-TES tool is available.

**Task Outcomes:**
- CWL-TES code modifications to support task intermediate remote inputs/outputs
- CWL-TES code modifications to support FTP protocol

**Comment by aniewielska** [comment]
That has been implemented and now cwl-tes can optionally use FTP as a store for inputs/outputs. The implementation assumes sharing access to the same FTP account on both cwl-tes and TESK side.
