### ISSUE TITLE
User Story: Integrate Workflow Repository to store user workflows

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#80]
As **a user**, I **would** like to store my workflows in a repository, **so that** I can use it to execute workflows on the GA4GH-CC platform.

**Comment by susheel** [comment]
- [ ] Investigate [GA4GH Tool Registry Service](https://github.com/ga4gh/tool-registry-service-schemas)
- [ ] [Biocontainers 2.0](https://github.com/BioContainers/registry-backend-api)

**Comment by susheel** [comment]
Biocontainers 2.0 is already implementing this as part of the ELIXIR Tools Platform

**Comment by aniewielska** [comment]
That work is currently happening or just about to happen. But not in TESK.
