### ISSUE TITLE
WES web UI front end

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#85]

**Comment by psafont** [comment]
Seven bridges have libraries to deal with cwl using typescript, that may be useful: https://github.com/rabix/cwl-ts

They use it for the rabix composer webapp: https://github.com/rabix/composer

**Comment by susheel** [comment]
ELIXIR-DE and CH have expressed an interest in this. Will follow it up with them.

**Comment by susheel** [comment]
Assigning myself. Will follow this up with ELIXIR DE and CH

**Comment by aniewielska** [comment]
That is really way beyond TESK, but a really nice project, which - among others - can be a WES web IU has been created here: https://github.com/CompEpigen/CWLab
