### ISSUE TITLE
Integrate Cromwell workflow engine Integration with TES

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#86]

**Comment by susheel** [comment]
Issue: MMG CWL Tool expects directory not to exist
Current CWL-TES solution: Sends link to entire workdir
Cromwell hack for using the entire workdir

**Comment by aniewielska** [comment]
This is the issue that we encountered in Cromwell-TESK, when running CWL-Assembly - TESK maps all nested directories for inputs and outputs as sub-paths of a PVC and that is why all of them are visible os existing, whereas some tools expect to create them. 
The solution at TESK side would be to detect nesting and only mount the upper level.
The solution on Cromwell side was implemented - not listing all detailed outputs, but the entire workdir.
