### ISSUE TITLE
Set up a separate OpenStack user to deploy Kubernetes

### ISSUE THREAD

**Issue by aniewielska** [EMBL-EBI-TSI/TESK#87]
At the moment we use personal Open Stack credentials to set up Kubernetes cluster. After that account was blocked by cloud team the cluster stopped working. OS credentials are kept in plain text on each K8s node.
So we need to:
- check, if there is a different (better?) way of storing OS credentials for Kube, than keeping them in plain text (if not - we will keep it as it is).
- set up an account to be used to deploy Kube clusters on Open Stack (so that we won't be using personal accounts).

**Comment by susheel** [comment]
@giannidallatorre Please check if this issue is still valid else update or close the issue

**Comment by giannidallatorre** [comment]
| username              | Open Stack | project (aka tenancy)|
|---|---|---|
|`ebi-ga4gh-tes`    |`extcloud06`|`EBI-GA4GH-TES`|
|`k8s_provisioning`|`extcloud05`|`EBI-TSI` `EBI-TSI-DEV`|

Passwords will be available off line (or in the Vault)

**Comment by aniewielska** [comment]
That has been done and apart from that, K8s - OpenStack integration has changed and for recent deployments we avoid Cinder altogether and that is the only reason we were using OpenStack cloud provider integration in K8s.
